/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for the OpenMCT external plugins index
 */
export interface OpenMCTPluginsIndex {
  /**
   * Reference to this schema
   */
  $schema?: string;
  /**
   * Array of available plugins
   */
  plugins: {
    /**
     * The npm package name or specifier for the plugin (e.g., 'akhenry/openmct-yamcs' or 'openmct-plugin@1.0.0')
     */
    npmPackageName: string;
  }[];
}
