# yaml-language-server: $schema=../../../src/assets/openmct-configuration-schema.json
openmct:
  version: stable
  plugins:
    - sunrise-calculation-plugin:
        npmPackage: file:./sunrise-calculation-plugin
        # options:
        #   latitude: 28.5729
        #   longitude: -80.6490
    - sunrise-plugin:
        npmPackage: file:./sunrise-plugin
        options:
          sunriseTime: ${sunriseTime}
          sunriseDate: ${sunriseDate}
          sunriseLatitude: ${sunriseLatitude}
          sunriseLongitude: ${sunriseLongitude}