/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for OpenMCT configuration YAML
 */
export interface OpenMctConfigurationSchema {
  openmct:
    | {
        /**
         * Version of OpenMCT to use
         */
        version: string;
        plugins?: (string | PluginMap)[];
      }
    | {
        /**
         * NPM package that provides Open MCT. If present this will override any Open MCT version specified.
         */
        npmPackage: string;
        plugins?: (string | PluginMap)[];
      };
}
export interface PluginMap {
  [k: string]: Plugin;
}
/**
 * This interface was referenced by `PluginMap`'s JSON-Schema definition
 * via the `patternProperty` "^.*$".
 */
export interface Plugin {
  source?: 'npm' | 'builtin';
  /**
   * NPM package that provides this plugin.
   */
  npmPackage?: string;
  /**
   * Name of the function that is exported from the npm package and which provides this plugin.
   */
  installFunction?: string;
  /**
   * Script that exports the install function(s)
   */
  entryPoint?: string;
  /**
   * Whether the plugin should be enabled. By setting this to false you can override default plugins
   */
  enabled?: boolean;
  /**
   * The options to be passed to the plugin at install time. Can be either an object or an array. If an array is provided, each member will be treated as an argument to the plugin install function.
   */
  options?: {} | unknown[];
}
