/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for OpenMCT configuration YAML
 */
export interface OpenMctConfigurationSchema {
  openmct: {
    /**
     * Version of OpenMCT to use
     */
    version?: string;
    plugins: (string | PluginMap)[] | PluginMap;
  };
}
export interface PluginMap {
    [name: string]: Plugin;
}
export interface Plugin {
  source?: 'npm' | 'github' | 'local' | 'builtin';
  /**
   * Version of the plugin to use
   */
  version?: string;
  /**
   * The options to be passed to the plugin at install time
   */
  options?: {};
}
