/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for OpenMCT configuration YAML
 */
export interface OpenMctConfigurationSchema {
  openmct:
    | {
        /**
         * Version of OpenMCT to use
         */
        version: string;
        plugins?: (string | PluginMap)[];
      }
    | {
        /**
         * NPM package that provides Open MCT. If present this will override any Open MCT version specified.
         */
        npmPackage: string;
        plugins?: (string | PluginMap)[];
      };
}
export interface PluginMap {
  [k: string]: Plugin;
}
/**
 * This interface was referenced by `PluginMap`'s JSON-Schema definition
 * via the `patternProperty` "^.*$".
 */
export interface Plugin {
  source?: 'npm' | 'builtin';
  /**
   * NPM package that provides this plugin.
   */
  npmPackage?: string;
  /**
   * Script that exports the install function
   */
  entryPoint?: string;
  /**
   * Whether the plugin should be enabled. By setting this to false you can override default plugins
   */
  enabled?: boolean;
  /**
   * The options to be passed to the plugin at install time
   */
  options?: {};
  [k: string]: unknown | undefined;
}
